### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by hissssst** [Vetspire/sibyl#36]
Hi, great idea for a library, but I think that it is extremely inefficient to perform __a check of every module in the system when emitting an event__ with `Sibyl.emit` (which calls `Event.event?` which calls `reflect/0` which loads and calls every module in the system)

First, you'll definitely need a prefix tree (or at least a `MapSet`) to perform `event?` efficiently.
Second, I'd just generate a function like `__sibyl_events__` which would return a list of events defined in the module, instead of looking into attributes (and attributes list can be huge)

Then, I can suggest doing one of 3 things:

1. As a user, I don't want to load every event by default. So I'd prefer to call something like `Sibyl.setup_events(list_of_apps or maybe list_of_modules or even list_of_events)` which would store a list of all events in `persisten_term`, and I'd have to manually call it on recompile if I want to load all events.

2. I don't think that I'd use a library which automatically loads all events from dependency, but if you think that this is the way to go, you should at least cache the result of `reflect/0` (and cache it in some search-optimized form)

3. Another solution is to setup a convention that every module emits an event with this name in prefix. For example, `Project.Context.Something` would emit `[:sibyl, :project, :context, :something, ...]`.  This would make this check somewhat more efficient (but you'd have to concat this prefix into multiple modules, etc). This is a bad solution, but it is still better than checking every module in the system

**Comment by vereis** [comment]
Ahoy @hissssst !! Thanks for your comments and apologies for the delays in replying to this!

> It is extremely inefficient to perform a check of every module in the system when emitting an event
Agreed! If I remember correctly, we mainly do the `reflect/0` call at compile time but we may indeed do this multiple times per emit.

Currently, I'm not sure this approach will impact runtime perf (which I want to care about a lot), but yeah, I'm definitely open to improving this at compile time, too!

> First, you'll definitely need a prefix tree (or at least a MapSet) to perform event? efficiently.

Agreed! I think adding a `__sibyl_events__(opts \\ Keyword.t()) :: MapSet.t()` function makes sense to me, which we can compile into modules that `use Sibyl` & define events.

I've never tried, but I wonder if we can just create an `:ets` table on the first invocation of `Sibyl.Events.reflect/0` at compile time and rely on that at compile time to quickly determine if events have been defined properly -- though maybe the `MapSet` is good enough?

> As a user, I don't want to load every event by default. So I'd prefer to call something like Sibyl.setup_events(list_of_apps or maybe list_of_modules or even list_of_events) which would store a list of all events in persisten_term, and I'd have to manually call it on recompile if I want to load all events.

When attaching a handler via `Sibyl.Handlers.attach_*_events/3` you can actually provide the list of events you care about.

You can call:

- `Sibyl.Handlers.attach_all_events/2` which will attach all defined events in all loaded modules to the specified handler
- `Sibyl.Handlers.attach_module_events/3` which will attach all defined events in the given module to the specified handler
- `Sibyl.Handlers.attach_events/3` which will attach the given list of raw telemetry events to the specified handler!

Any `Sibyl.Events.reflect/0-1` usage will thus only be called once at setup time. I'm not sure we need to provide a `persistent_term` cache as `Sibyl`s emission checks and the like are largely compile time.

WDYT?

> I don't think that I'd use a library which automatically loads all events from dependency, but if you think that this is the way to go, you should at least cache the result of reflect/0 (and cache it in some search-optimized form)

Agree! I'm prone to wanting to throw it in an ETS table for ease and familiarity but open to other suggestions!

> Another solution is to setup a convention that every module emits an event with this name in prefix. For example, Project.Context.Something would emit [:sibyl, :project, :context, :something, ...]. This would make this check somewhat more efficient (but you'd have to concat this prefix into multiple modules, etc). This is a bad solution, but it is still better than checking every module in the system

I'm open to adding a `prefix` option to `Sibyl` if this is something people have a use case for! But agreed that I don't think we should do this purely for the ability to provide more efficient searching.

Please let me know if I've misunderstood any of your points! Thank you for your feedback and trying to help make `Sibyl` better!

**Comment by hissssst** [comment]
Yeah, right, I've missed that it's in `defmacro`. However, I've found a lot of other bugs, while giving it a deeper look
